###################################################################
# Local syslog-ng configuration filter definition [sshd].
# Captures SSH session access logs from the sshd daemon.
###################################################################
filter f_local_sshd {
    program("sshd");
};
